services:
  beaker:
    image: beaker-dev:latest
    ports:
      - "8888:8888"
    volumes:
      - "home:/home/user"
      - ".:/opt/development/packages/beaker-notebook"
    pull_policy: never

  ui:
    build:
      context: .
      dockerfile_inline: |
        FROM node:24
        USER root:root
        RUN apt update && apt install -y vim
        RUN npm install -g npm@11.3.0
        RUN echo 'prefix = "/home/node"' > /home/node/.npmrc
        COPY . /home/node/
        RUN chown -R node:node /home/node
        VOLUME /home/node/node_modules /home/node/beaker-vue /home/node/beaker-vue/node_modules /home/node/beaker-ts /home/node/beaker-ts/node_modules /home/node/beaker-vue/dist/html
        USER node:node
        WORKDIR /home/node/
        RUN echo '{\n\
            "workspaces": [ "beaker-ts", "beaker-vue" ]\n\
        }' > /home/node/package.json
        RUN npm i --workspaces
    user: node:node
    volumes:
      - node-modules:/home/node/node_modules
      - ./beaker-vue:/home/node/beaker-vue
      - vue-modules:/home/node/beaker-vue/node_modules
      - ./beaker-ts:/home/node/beaker-ts
      - ts-modules:/home/node/beaker-ts/node_modules
      - ui-html:/home/node/beaker-vue/dist/html
    working_dir: "/home/node"
    healthcheck:
      test: [ "CMD", "ls", "/home/node/beaker-vue/dist/html/routes.json"]
      interval: 5s
      timeout: 10s
      retries: 36  # 3 minutes
      start_period: 5s
    environment:
      - PROXY=http://beaker:8888
      - UID=1000
      - GID=1000
    ports:
      - "8080:8080"
    command: |
      sh -c '
        npm i;
        npm -w beaker-vue run routes;
        npm -w beaker-vue run serve;
      '

volumes:
  home:
  node-modules:
  vue-modules:
  ts-modules:
  ui-html:
